play_motion:
  motions:
    rest_head:
      joints: [head_1_joint, head_2_joint]
      points:
        - time_from_start: 1
          positions: [0.002366301372505042, -0.8148519747609053]
      meta:
        name: rest_head
        usage: rest_head
        description: rest point for the robot's head
