play_motion:
  motions:
    noddling_no:
      joints: [head_1_joint, head_2_joint]
      points:
        - time_from_start: 0
          positions: [0.002366301372505042, -0.8148519747609053]
        #go to p13
        - time_from_start: 0.3
          positions: [ 0.195721242047712, -0.8240673132114353]
        - time_from_start: 0.7
          positions: [-0.1879168598191919, -0.8240673132114353]
        - time_from_start: 1.3
          positions: [0.002366301372505042, -0.8148519747609053]

        #come back
      meta:
        name: noddling_no
        usage: noddling_no
        description: head noddling
